-- Receipt numbers for payments: every recorded payment gets a club-wide
-- sequential number so cash/EFT can be receipted properly, plus a free-text
-- note (e.g. "term 1 fees", "paid at training").
alter table payments add column receipt_no bigint generated by default as identity;
alter table payments add column note text not null default '';
